name: E2E iOS Tests

on:
    pull_request:
        types: [opened, synchronize]

env:
    DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer

jobs:
    check_diff:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup git
              run: |
                  git fetch
                  git checkout
            - name: Check diff
              run: echo $(git diff $(find . -regextype posix-extended -regex "\.\/(src|ios|assets|(tests\/(e2e|utils))|__mocks__|\.env.*|[^\/]*.js(on)?)"))
    test:
        needs: check_diff
        runs-on: macos-10.15
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-ruby@v1
              with:
                ruby-version: '2.7'

            - name: Install bundler
              run: gem install bundler

            - name: Install gems
              run: bundle install

            - name: Install node packages
              run: npm install

            - name: Install detox
              run: npm install -g detox-cli

            - name: Install cocoapods
              run: cd ios && pod install --repo-update

            - name: Install brew depdencies
              run: |
                brew tap wix/brew
                brew install applesimutils

            - name: Build tests
              run: detox build --configuration ios.sim.release

            - name: Run tests
              run: detox test --configuration ios.sim.release --cleanup --debug-synchronization 200 --loglevel trace
