name: Jest Unit Tests

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v1

            - run: npm install

            - name: Generate version
              uses: Expensify/Expensify.cash/.github/actions/bumpVersion@master
              with:
                  GITHUB_TOKEN: ${{ secrets.OS_BOTIFY_TOKEN }}

            - run: npm run test
              env:
                  CI: true
